name: build-zk-armv7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine

    steps:
      - name: Instalar dependências e compilador ARMv7
        run: |
          apk add --no-cache git build-base musl-dev gcc-armhf g++-armhf

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build static armv7 binary
        env:
          CGO_ENABLED: '1'
          GOOS: linux
          GOARCH: arm
          GOARM: '7'
          CC: armv7-alpine-linux-musleabihf-gcc
          CXX: armv7-alpine-linux-musleabihf-g++
        run: |
          go build \
            -tags "fts5 netgo osusergo" \
            -ldflags '-linkmode external -extldflags "-static"' \
            -o zk-armv7 .

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zk-armv7
          path: zk-armv7
