name: build-zk-armv7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar a Release no repositório

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install ARMv7 Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            g++-arm-linux-gnueabihf

      - name: Check Toolchain
        run: |
          arm-linux-gnueabihf-gcc --version
          arm-linux-gnueabihf-gcc -dumpmachine

      - name: Build static armv7 binary
        env:
          CGO_ENABLED: '1'
          GOOS: linux
          GOARCH: arm
          GOARM: '7'
          CC: arm-linux-gnueabihf-gcc
          CXX: arm-linux-gnueabihf-g++
        run: |
          go build \
            -tags "fts5 netgo osusergo" \
            -ldflags '-linkmode external -extldflags "-static"' \
            -o zk-armv7 .

      - name: Check Binary
        run: |
          file zk-armv7
          ls -lh zk-armv7

      - name: Create Nightly/Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "zk ARMv7 Build"
          body: "Binário estático compilação ARMv7 para Android/Termux"
          files: zk-armv7
